name: Linux builds (basic)

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-12
          - g++-13
          - g++-14
          - clang++-16
          - clang++-17
          - clang++-18
        build_type: [Debug] #, Release]
        std: [20]
        include:
        # cannot be installed on ubuntu-24.04 be default?
          - cxx: g++-12
            cc: gcc-12
            other_pkgs: g++-12
          - cxx: g++-13
            cc: gcc-13
            other_pkgs: g++-13
          - cxx: g++-14
            cc: gcc-14
            other_pkgs: g++-14
          - cxx: clang++-16
            cc: clang-16
            other_pkgs: clang-16
          - cxx: clang++-17
            cc: clang-17
            other_pkgs: clang-17
          - cxx: clang++-18
            cc: clang-18
            other_pkgs: clang-18

    steps:
    - uses: actions/checkout@v2

    - name: Prepare environment
      env:
        TZ: "America/Los_Angeles"
      run: |
        sudo ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime
        echo ${TZ} | sudo tee /etc/timezone
        sudo apt-get update -q
        sudo apt-get install -y -y --no-install-recommends \
          ${{matrix.other_pkgs}} \
          build-essential \
          xorg-dev \
          libmotif-dev \
          libfreetype6-dev \
          cmake \
          git \
          xwit \
          xfonts-base \
          xfonts-75dpi \
          xfonts-100dpi \
          tzdata \
          libcurl4-gnutls-dev

    - name: Configure build
      working-directory: ${{runner.workspace}}
      env:
        CC: ${{matrix.cc}}
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
      #       This is important
      run: |
        cmake -S $GITHUB_WORKSPACE -B _build_${{matrix.cxx}}_${{matrix.std}} \
          -DCMAKE_INSTALL_PREFIX="${PWD}/_install_${{matrix.cxx}}_${{matrix.std}}" \
          -DCMAKE_BUILD_TYPE="${{matrix.build_type}}" \
          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
          -DCMAKE_CXX_EXTENSIONS=OFF \
          -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Verify directory structure
      run: |
        echo "Verifying new directory structure..."
        ls -la src/
        ls -la src/core/ src/utils/ src/network/
        ls -la main/business/ main/hardware/ main/ui/ main/data/
        ls -la scripts/build/ scripts/install/ scripts/system/ scripts/maintenance/ scripts/tools/
        ls -la assets/images/xpm/ assets/data/po_file/
        ls -la config/ docs/ fonts/

    - name: Build + install
      working-directory: ${{runner.workspace}}
      run: |
        cmake --build _build_${{matrix.cxx}}_${{matrix.std}} -j2
        cmake --build _build_${{matrix.cxx}}_${{matrix.std}} --target install
